/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import matchmaking.QuestionScreen;
import usersPKG.student;

/**
 *
 * @author dunca (Duncan)
 */
public class ifGenderOrOriNULL extends javax.swing.JFrame {
student s;
     /**
     * Creates new form ifGenderOrOriNULL
     */
    public ifGenderOrOriNULL()  {
        initComponents();
    }
    
    
    /**
     * Creates new form ifGenderOrOriNULL
     */
    public ifGenderOrOriNULL(student s) {
        initComponents();
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genMale = new javax.swing.JButton();
        genFem = new javax.swing.JButton();
        genOther = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oriMen = new javax.swing.JButton();
        oriFem = new javax.swing.JButton();
        oriBi = new javax.swing.JButton();
        oriAny = new javax.swing.JButton();
        continuebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        genMale.setText("Male");
        genMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genMaleActionPerformed(evt);
            }
        });

        genFem.setText("Female");
        genFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFemActionPerformed(evt);
            }
        });

        genOther.setText("Don't want to say/other");
        genOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genOtherActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("My Gender is...");

        jLabel2.setText("I'm looking for...");

        oriMen.setText("Boys");
        oriMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oriMenActionPerformed(evt);
            }
        });

        oriFem.setText("Girls");
        oriFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oriFemActionPerformed(evt);
            }
        });

        oriBi.setText("Boys/Girls");
        oriBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oriBiActionPerformed(evt);
            }
        });

        oriAny.setText("Anyone");
        oriAny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oriAnyActionPerformed(evt);
            }
        });

        continuebutton.setText("CONTINUE");
        continuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genFem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(continuebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oriAny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oriMen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oriFem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oriBi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(genMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genFem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genOther))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(oriMen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oriFem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oriBi)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oriAny)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continuebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genMaleActionPerformed
        // TODO add your handling code here:
        s.setGen(1);
    }//GEN-LAST:event_genMaleActionPerformed

    private void oriMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oriMenActionPerformed
        // TODO add your handling code here:
        s.setOri(1);
    }//GEN-LAST:event_oriMenActionPerformed

    private void continuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebuttonActionPerformed
        // TODO add your handling code here:
        //check to see if gender and/or orientation are entered
        if (s.getOri() == 0 && s.getGender() == 0)  {
           JOptionPane.showMessageDialog(this, "Please enter your orientation and gender.");
        }
        else if (s.getOri() == 0)    {
           JOptionPane.showMessageDialog(this, "Please enter your orientation.");
        }
        else if (s.getGender() == 0)    {
           JOptionPane.showMessageDialog(this, "Please enter your gender.");
        }
        
        //if both present, send it to question screen with student
        
        /* Create and display the form */
        else    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionScreen(s).setVisible(true);
            }
        });
        //get rid of the screen
        this.dispose();
        }
    }//GEN-LAST:event_continuebuttonActionPerformed

    private void genFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFemActionPerformed
        // TODO add your handling code here:
        s.setGen(2);
    }//GEN-LAST:event_genFemActionPerformed

    private void genOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genOtherActionPerformed
        // TODO add your handling code here:
        s.setGen(3);
    }//GEN-LAST:event_genOtherActionPerformed

    private void oriFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oriFemActionPerformed
        // TODO add your handling code here:
        s.setOri(2);
    }//GEN-LAST:event_oriFemActionPerformed

    private void oriBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oriBiActionPerformed
        // TODO add your handling code here:
        s.setOri(4);
    }//GEN-LAST:event_oriBiActionPerformed

    private void oriAnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oriAnyActionPerformed
        // TODO add your handling code here:
        s.setOri(3);
    }//GEN-LAST:event_oriAnyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ifGenderOrOriNULL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ifGenderOrOriNULL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ifGenderOrOriNULL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ifGenderOrOriNULL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ifGenderOrOriNULL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuebutton;
    private javax.swing.JButton genFem;
    private javax.swing.JButton genMale;
    private javax.swing.JButton genOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton oriAny;
    private javax.swing.JButton oriBi;
    private javax.swing.JButton oriFem;
    private javax.swing.JButton oriMen;
    // End of variables declaration//GEN-END:variables
}
